americanexpress/eslint-config-amex

README.md

This also switches to shields.io for badges

docs(readme): center image

---

package-lock.json
package.json

I tried running `npm dedupe` on this, but the `package.spec.js` test kept failing. Maybe we should look into that in the future?

chore(deps): update lockfile-lint

---

index.js

Expand the AirBnB boolean prop names with a few more options

fix(eslint): boolean prop naming

---

index.js

React requires use of null and this rule conflicts with that.

fix(eslint): react requires use of null

---

index.js

Enable react/recommended rules (somehow this was overlooked), adds the missing React hooks rule, and other minor rules that generally help with React and JSX.

feat(eslint): react/jsx quality of life rules

---

index.js

This inherited rule from the import rule set should be disabled

feat(eslint): disable prefer default export

---

index.js

Added some missing configuration settings. Also added support for src as a resource root.

feat(eslint): configuration

---

__tests__/unicorn.js
index.js
package-lock.json
package.json
unicorn.js

Updated Unicorn and no longer using `recommended` rule set. We now explicitly include each rule to help avoid future rule surprises.  
Rules with `******` I am unsure about including. Will remove before merging.

feat(unicorn): update and seperate rules

---

CONTRIBUTING.md
__tests__/package.spec.js
package-lock.json
package.json

BREAKING CHANGE:
- Several ESLint plugins received major updates.
- ESLint versions below v7.15.0 are no longer supported.
Fixed the asynchronous function call in the test for peer dependency warnings.
Updated all `devDependencies` and `dependencies` to their latest versions to resolve the warnings. This caused new warnings because some dependencies have recently dropped support for ESLint versions below v7. Updated ESLint to v7 to fix these warnings.
There were several peer dependency warnings output while installing `eslint-config-amex`.  The test for these warnings was missing the `await` keyword on the call to `exec`. The promise assignment would then destructure the `stdout` and `stderr` variables as `undefined` which would always pass the test.
No new tests needed.

feat: fix the peer dep test; update all deps to latest

---

index.js
unicorn.js

Update the links to rule descriptions to use the tagged release instead of master branch.
Some of the links in the unicorn.js comments are 404ing because it is linking to the master branch and some of the rules were removed in later releases.
For instance:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prefer-trim-start-end.md
vs
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v20.1.0/docs/rules/prefer-trim-start-end.md
Linking to the specific versions that are used as dependencies should make this more stable.
n/a

fix(comments): link to tagged releases instead of master

---

__tests__/prettier/index.spec.js
__tests__/prettier/test.spec.js
__tests__/test.spec.js
index.js
package-lock.json
package.json
prettier/index.js
prettier/test.js
test.js

This PR upgrades eslint-plugin-unicorn. This version brings config options that use inclusive language.
This required a minor upgrade to eslint.
Repositories that consume this eslint config, and wish to override 'unicorn/prevent-abbreviations' need to use non-inclusive language in their config. This change brings in a version of the unicorn package where they reworded all their config options to only use inclusive language.

feat(unicorn): upgrade eslint-plugin-unicorn from 23.0.0 to 36.0.0

---

package-lock.json
package.json

the typescript semver range is causing peerDep conflicts, i am unable to find a reason for not using >=4.2.0

fix(typescript): peer dep conflict

---

index.js
package-lock.json
package.json

chore(deps): update eslint-plugin-markdown to 2.2.1

---

package.json

Allow eslint-config-amex to work with eslint-plugin-prettier@4

fix(eslint-plugin-prettier): peer version

---

index.js
package-lock.json
package.json

The `babel-eslint` package was deprecated at v10.1.0 and
moved to `@babel/eslint-parser`.
Replaced the deprecated `babel-eslint` dependency with `@babel/eslint-parser`. Added the `requireConfigFile` flag to the `parserOptions` key and disabled the requirement.
The `babel-eslint` package was deprecated at v10.1.0 and moved to the Babel monorepo as `@babel/eslint-parser`. This package must not depend on deprecated packages and should stay current with the Babel ecosystem.
I ran `npm  ci`, followed by `npm test`.

chore(deps): replace `babel-eslint` with `@babel/eslint-parser`

---

.github/workflows/tests.yml

Adds the ESLint version to the `tests` matrix job to test against multiple major versions.
This change also disables `fail-fast` so that all matrix jobs run. This could help with troubleshooting broken dependencies.
I would like to add support for ESLint 8.x. Many existing projects depend on ESLint 7.x and ideally this package can continue supporting that version after support for 8.x is introduced. I have a follow-up feature on the way for widening peer dependencies to make it easier to upgrade older codebases to recent versions of `eslint-config-amex`.
It may also be useful to extend matrix jobs for tests to include each preset flavor (`test`, `prettier`, etc.).
This change can be tested locally by using the same command line used …

feat(workflows): add supported ESLint versions to matrix for `tests`

---

index.js

I changed the link including the term `master` to the current link where `master` branch is now `main`.
There's an ESLint warning when running tests. This removes the warning.
`npm test`

fix: update link to remove non-inclusive term

---

index.js

feat(max-len): ignore described eslint ignores

---

package-lock.json
package.json

Closes #105.
Widens the semver ranges used for the `eslint-plugin-jest` and `eslint-plugin-jest-dom` peer dependencies to include their most recent major releases.
* Widen `eslint-plugin-jest` semver range to include [v26.0.0](https://github.com/jest-community/eslint-plugin-jest/releases/tag/v26.0.0)
* Widen `eslint-plugin-jest-dom` semver range to include [v4.0.0](https://github.com/testing-library/eslint-plugin-jest-dom/releases/tag/v4.0.0)
* Update `devDependencies` in `package.json` to depend on latest major releases of both packages
For tidiness, `package-lock.json` was deduplicated and committed after testing the above fixes.
See #105.
`npm test`

fix(peerDeps): widen semver ranges of ESLint plugins for Jest

---

package-lock.json
package.json

Update Jest to [v28](https://github.com/facebook/jest/releases/tag/v28.0.0).
Jest v28 offer many improvements over previous versions. This is part of an effort to modernize this package, starting with outdated dependencies.
`npm test`

test(setup): update Jest to v28

---

package-lock.json
package.json

Updates prettier peer dependency to support the current version 3
This allows users of this library to upgrade their prettier dependency without conflicting peer dependency. The current version of `eslint-config-amex` has a peer dep error when used with the current version of `prettier`.
```
› npm ls prettier
npm ERR! code ELSPROBLEMS
npm ERR! invalid: prettier@3.2.5 /[...]/ node_modules/prettier {module}@1.6.0 [...]/{module}
├─┬ eslint-config-amex@16.0.0
│ └─┬ prettier@3.2.5 deduped invalid: "^2.0.0" from node_modules/eslint-config-amex
└── prettier@3.2.5 invalid:"^2.0.0" from node_modules/eslint-config-amex
```
Tested using `npm pack`, installed in a module using prettier 3.2.5 and peer dep errors were resolved:
````
› npm ls prettier
{module}@1.6.0 [...]/{module}
├─┬ …
```

feat(dependencies): add support for prettier 3

---

package-lock.json
package.json

chore(deps): eslint-plugin-prettier also v5
