index.js
At the moment this rule ```jsx-one-expression-per-line``` would change this
```<div>{x} * {y} = {xy}</div>```
to this 
```
<div>
{x}
{' '}
*
{y}
{' '}
=
{' '}
{xy}
</div>
```
which makes it messy and unreadable. Until this is resolved https://github.com/yannickcr/eslint-plugin-react/issues/1848. Im proposing we disable this rule
=> feat(index): disable jsx-one-expression-per-line

index.js
When my .eslintrc file is this:
```
{
"extends": "amex"
}
```
The following code does not trigger any warnings / errors:
```
if (!(((((child.data)))))) {
return child.children.map((c) => c.data);
}
```
However including that extra rule directly via
```
{
"extends": "amex",
"rules": {
"no-extra-parens": "error"
}
}
```
makes the error appear:
=> feat(rules): no-extra-parens

package-lock.json, package.json
BREAKING CHANGE: Updates deps major versions
So the reason why `typescript` was due to the latest version of `eslint-plugin-jest` which has a dependency on `@typescript-eslint/experimental-utils` which has a dependency on `@typescript-eslint/typescript-estree` which has a dependency on `tsutils` which apparently requires `typescript`.
Furthermore, this now fixes optional chaining which was throwing a linting error due to `babel-eslint` being a `v7` instead of `v10`
**Changes for `babel-eslint`**
From 7 to 8:
* No major changes, just updating babel deps to v7
From 8 to 9:
* Babel removed the support for Node 4 , so I propagated that here. 
* supports the new decorators proposal by default
From 9 to 10:
* Drop monkeypatching behavior
* add a peerDependency starting from the ESLint version …
=> feat(deps): update dependencies to latest version

.github/workflows/stale.yml
This PR does the following:
- Adds stale action v3
- Adds `days-before-close` to `-1` so it doesn't close anything (https://github.com/actions/stale/blob/master/action.yml#L16)
- Adds `exempt-issue-labels` and `exempt-pr-labels`
=> chore(workflow): add stale workflow

index.js
I am fundamentally opposed to these rules which are inherited from AirBnB. We can discuss it, but I have very good reasons why I am against them.
They require writing more code, not less. They give developers who don't truly understand how default props work false confidence. They are primarily beneficial when writing a library of components for public consumption, but are far too burdensome when writing regular components inside of a typical application. If you're writing a library for public consumption, tests are far more reliable than this burdensome rule.
The implied value of any undefined variable in JavaScript is undefined. We don't need to declare that as the default value. And that's what these rules end up doing. Every code base I have seen with these rules enabled is full of …
=> fix(eslint): disable airbnb default props rules

index.js
This is a questionable rule. As stated in the comment above the rule, Array.includes() is a consistent api with String.includes(). Further, any alleged performance increase is almost assuredly imperceptible in most cases and is thus a premature optimization.
=> feat(eslint): array includes is acceptable

index.js
Preventing abbreviations is incompatible with React standards (props, ref, etc.). Additionally, there are many scenarios where abbreviations are acceptable.
In the future, we may decide to make a whitelist, but since that will take time to decide and this rule is currently in the published ruleset, we are releasing it with the rule disabled for now to address this problem quickly.
=> fix(eslint): disable prevent abbreviations

index.js
This is a common pattern in React. The source of the measurements used as the basis for this rule were found to have been taken in the development version of React and were disproven. However, the myth persists. The React team has stated that this optimization is not necessary.
=> feat(eslint): disable function scoping

index.js
Thought we could live with warn but i was wrong.
=> feat(unicorn/consistent-function-scoping): disable

package-lock.json, package.json, prettier.js
Use `eslint-plugin-prettier` package to:
• Turns off eslint errors that conflict with prettier (using `eslint-config-prettier` internally)
• Adds eslint errors when prettier rules are violated
• Allows using your code editor's prettier plugin OR eslint --fix to fix all eslint and prettier errors.
=> feat(prettier): enforce prettier on amex/prettier

unicorn.js
Disabling this rule as Internet Explorer does not have support for `.includes()`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
=> feat(unicorn/prefer-includes): disable

README.md, __tests__/package.spec.js, package-lock.json, package.json
**NOTE:** This is waiting on #61 so has been raised as a draft while that one is reviewed. Once that PR is updated, I'll rebase against `main`.
Make all optional dependencies optional peer dependencies. After this change, to use `amex/test` you will need to install required peer dependencies:
```bash
npm install --save-dev typescript eslint eslint-plugin-jest eslint-plugin-jest-dom eslint-config-amex
```
To use `amex/prettier/test` you will need to use:
```bash
npm install --save-dev prettier typescript eslint eslint-plugin-jest eslint-plugin-jest-dom eslint-plugin-prettier eslint-config-amex
```
This package provides a main ESLint configuration and a few optional ones. The optional ones are specified as dependencies. In particular …
=> BREAKING CHANGE: Feat/move tools to peer deps

package-lock.json
When running the unit tests locally, the following error is displayed:
```sh
❯ npm test
> eslint-config-amex@14.0.0 test /Users/mrbrown/src/github.com/americanexpress/eslint-config-amex
> npm run test:unit
> eslint-config-amex@14.0.0 test:unit /Users/mrbrown/src/github.com/americanexpress/eslint-config-amex
> jest
PASS  __tests__/unicorn.js
PASS  __tests__/index.spec.js
PASS  __tests__/prettier/index.spec.js
PASS  __tests__/prettier/test.spec.js
PASS  __tests__/test.spec.js
FAIL  __tests__/package.spec.js (6.525 s)
● package.json › should not have peer dep warnings
Command failed: npm ls
npm ERR! peer dep missing: marked@>=0.4.0 <2.0.0, required by marked-terminal@4.1.0
● package.json › should not have peer dep warnings
expect.assertions(2)
Expected two assertions to be called but …
```
=> chore: upgrade `marked-terminal` to v4.1.1

index.js, package-lock.json, package.json
Adds the "inclusive-language/use-inclusive-words" rule:
https://github.com/muenzpraeger/eslint-plugin-inclusive-language
The list of words is explicit to reduce the chance of unintended changes from the upstream dependency.
The rule is currently marked as a warning. Not sure if an error would be warranted? 
Using inclusive coding terms is essential to creating an inclusive environment. And anything that can be automatically tested by eslint should be.
Ran `npm pack` and installed the repo against an existing repository that was using the existing lint config.  After adding a violation to the code, running eslint generated the expected warning:
```
10:3   warning  The usage of the non-inclusive word 'master' is discouraged, use …
```
=> feat(eslint): add inclusive-language rule

index.js
Change from error to warning to remove breaking change
=> fix(index): switch inclusive language to warning

.github/workflows/health-check.yml, .github/workflows/tests.yml, CONTRIBUTING.md, package.json
BREAKING CHANGE: Node v10 has reached end-of-life and is no longer supported.
Removed Node v10 from CI, added Node v16 to CI, added `engines` property to `package.json` with support for Node v12 and later.
Node v10 reached end-of-life on April 30th, 2021.
`npm install` followed by `npm test` in Node v16.
=> feat: remove Node v10 support and add support for Node v16

__tests__/index.spec.js, __tests__/prettier/index.spec.js, __tests__/prettier/test.spec.js, __tests__/test.spec.js, __tests__/unicorn.js, index.js, package-lock.json, package.json
[eslint-plugin-eslint-comments](https://www.npmjs.com/package/eslint-plugin-eslint-comments)
BREAKING CHANGE: [7 new rules](https://github.com/mysticatea/eslint-plugin-eslint-comments/tree/master/docs/rules) added as errors
Usually eslint directives are overrides of a preset or project-level configuration. There are situations where an override may be the best path. This plugin helps those instances to be applied to the right location, record the reasoning behind the override, prevent unintended side-effects (ex: applying to more locations by forgetting to re-enable the rule), and remove unused rule violation overrides.
Most visible to developers will be [eslint-comments/require-description](https://github.com/mysticatea/eslint-plugi …
=> feat(eslint-comments): aid maintainability of eslint directives

index.js
Nesting controls inside of label has poor support in assistive technologies, instead enforce separate tags with an htmlFor on the label.
=> feat(ally): disallow nesting of controls in labels

package-lock.json, package.json
eslint-plugin-jest released a new major version, peer dep requirements preventing users from using 27.x.x
updated dev dep to use `27.0.1` of eslint-plugin-jest, ran tests on node 14, 16 before reverting version bump as tests fail in node 12
=> fix(eslint-plugin-jest): allow 27.x peer dep

index.js
Marks the vite / vitest config files as development files so that the `import/no-extraneous-dependencies` rule works properly.
Without this, eslint throws an error saying any imports they use should be added to dependencies not devDependencies.
Packed and installed in a repo using vitest.
=> feat: treat vite config files as dev files

index.js
For `import/no-extraneous-dependencies` rule, support both typescript and javascript extensions.
For the purposes of this rule, typescript vs javascript is not relevant and both should be supported.
Packed and installed in repo using this ruleset and verified resolves error.
=> feat: support typescript extensions

.github/workflows/ci.yml
Github disables scheduled workflows after 60 days of inactivity.  Since this workflow is both the PR check workflow and scheduled, this effectively means PR checks are disabled after 60 days of inactivity until an admin re-enables them.
This seems annoying enough that it's not worth having the scheduled runs.
=> chore(workflows): remove scheduled CI run

README.md
Add a note on the different quote styles between prettier and eslint-config-amex and how to resolve.
Code that uses prettier shouldn't be formatted that differently from code that doesn't.
N/A
=> docs(readme): add comment on prettier config

index.js
We support `__mocks__` and `mock` but not `mocks` as dev directories.
People who run into this rule tend to just install the dependencies as non-dev, which isn't good.
Verified that released version triggered `import/no-extraneous-dependencies` for `mocks` dir.
Verified that PR version did not trigger rule for `mocks` dir.
Verified that PR version did not trigger rule for `mock` or `__mocks__` (regression).
Verified that PR version did trigger for `foo` dir (regression).
=> feat: support mocks dir as dev directory

package-lock.json, package.json
Updates eslint-plugin-jest and eslint-plugin-jest-dom to allow latest version as peer deps.
Part of #132. Latest versions support eslint@9.
Major release notes:
https://github.com/testing-library/eslint-plugin-jest-dom/releases/tag/v5.0.0
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v28.0.0
Installed in a repo and verified that the newer versions of these deps could be installed without peer dep errors
```
$ npm i --save-dev eslint-plugin-jest@28
added 3 packages, removed 23 packages, changed 9 packages, and audited 2072 packages in 43s
$ npm i --save-dev eslint-plugin-jest-dom@5
changed 2 packages, and audited 2072 packages in 43s
```
Verified eslint still runs as expected.
```
$ npm run test:lint
> test-package@0.0.0 test:lint
> eslint --ignore-path .gitignore --ext …
```
=> feat(deps): support latest eslint-plugin-jest and eslint-plugin-jest-dom

.npmrc, package-lock.json, package.json
Use a semver range for @babel/eslint-parser.
When this was added in https://github.com/americanexpress/eslint-config-amex/pull/94, a fixed version was used rather than a semver.  There is no rationale for this in the PR, so I assume this was a mistake.
As a result, every consuming package has a fixed version:
```
$ npm ls @babel/eslint-parser
...
└─┬ eslint-config-amex@16.5.0
└── @babel/eslint-parser@7.16.5
```
@babel/eslint-parser@7.24.5 is required to support eslint@9 so this is part of #132 
Packed and verified version in consumers is no longer fixed.
```
$ npm ls @babel/eslint-parser
...
└─┬ eslint-config-amex@16.5.0
└── @babel/eslint-parser@7.25.9
```
=> fix(deps): use semver for @babel/eslint-parser

.npmrc
Adds an `.npmrc` file that points to the default npm registry.
Ensures that default registry is used for package-lock.json rather than private mirror registries.
Verified it works as expected.
=> chore: add .npmrc pointing to default registry
